# Generated by Django 4.2.27 on 2025-12-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
